"""
平台扫码登录提供者抽象基类

定义所有平台Provider必须实现的接口。
"""

import time
import logging
from abc import ABC, abstractmethod
from typing import Dict, Any, List, Optional

from .models import QRCodeResult, QRLoginResult, QRLoginStatus

logger = logging.getLogger(__name__)


class PlatformQRProvider(ABC):
    """平台扫码登录提供者抽象基类
    
    所有平台的扫码登录Provider都必须继承此类并实现抽象方法。
    """
    
    @property
    @abstractmethod
    def platform_id(self) -> str:
        """平台ID（唯一标识符，如 'bilibili', 'douyin'）"""
        pass
    
    @property
    @abstractmethod
    def platform_name_zh(self) -> str:
        """平台中文名称（如 '哔哩哔哩', '抖音'）"""
        pass
    
    @property
    @abstractmethod
    def qr_expiry_seconds(self) -> int:
        """二维码过期时间（秒）"""
        pass
    
    @property
    def platform_domain(self) -> str:
        """平台域名（用于Cookie过滤，子类可覆盖）"""
        return f".{self.platform_id}.com"
    
    @abstractmethod
    async def generate_qrcode(self) -> QRCodeResult:
        """生成登录二维码
        
        Returns:
            QRCodeResult: 包含二维码URL、key、过期时间和提示消息
            
        Raises:
            Exception: 生成二维码失败时抛出异常
        """
        pass
    
    @abstractmethod
    async def check_login_status(self, qrcode_key: str) -> QRLoginResult:
        """检查扫码登录状态
        
        Args:
            qrcode_key: 二维码唯一标识
            
        Returns:
            QRLoginResult: 包含状态、消息和Cookie（如果登录成功）
        """
        pass
    
    def convert_to_netscape(self, cookies: List[Dict[str, Any]]) -> str:
        """将Cookie列表转换为Netscape格式
        
        通用实现，子类可以覆盖以处理特殊情况。
        
        Args:
            cookies: Cookie字典列表，每个字典包含:
                - name: Cookie名称
                - value: Cookie值
                - domain: 域名
                - path: 路径（可选，默认'/'）
                - secure: 是否安全（可选，默认False）
                - expiry/expires: 过期时间戳（可选）
                
        Returns:
            Netscape格式的Cookie字符串
        """
        lines = [
            "# Netscape HTTP Cookie File",
            "# Generated by VidFlow QR Login",
            ""
        ]
        
        for cookie in cookies:
            name = cookie.get('name', '')
            if not name:
                logger.warning(f"跳过无效Cookie: name为空")
                continue
            
            domain = cookie.get('domain', '')
            if not domain:
                logger.warning(f"跳过无效Cookie: domain为空, name={name}")
                continue
            
            # 设置domain_specified标志
            # 如果域名以.开头，表示匹配所有子域，flag应该是TRUE
            flag = 'TRUE' if domain.startswith('.') else 'FALSE'
            
            path = cookie.get('path', '/') or '/'
            secure = 'TRUE' if cookie.get('secure', False) else 'FALSE'
            
            # 处理过期时间
            expiry = cookie.get('expiry') or cookie.get('expires') or 0
            if expiry == 0:
                # 会话Cookie，设置为1年后过期
                expiry = int(time.time()) + 365 * 24 * 3600
            
            value = cookie.get('value', '')
            
            # Netscape格式: domain flag path secure expiration name value
            line = f"{domain}\t{flag}\t{path}\t{secure}\t{expiry}\t{name}\t{value}"
            lines.append(line)
        
        return '\n'.join(lines)
    
    def convert_httpx_cookies_to_netscape(self, cookies) -> str:
        """将httpx响应的cookies转换为Netscape格式
        
        Args:
            cookies: httpx.Cookies对象
            
        Returns:
            Netscape格式的Cookie字符串
        """
        cookie_list = []
        for cookie in cookies.jar:
            cookie_dict = {
                'name': cookie.name,
                'value': cookie.value,
                'domain': cookie.domain,
                'path': cookie.path,
                'secure': cookie.secure,
                'expiry': cookie.expires,
            }
            cookie_list.append(cookie_dict)
        
        return self.convert_to_netscape(cookie_list)
    
    async def cleanup(self):
        """清理资源（如关闭浏览器）
        
        子类可以覆盖此方法来清理特定资源。
        默认实现不做任何操作。
        """
        pass
    
    def get_default_headers(self) -> Dict[str, str]:
        """获取增强版默认HTTP请求头（模拟真实Chrome浏览器）

        Returns:
            默认请求头字典
        """
        return {
            # 核心请求头（按Chrome真实顺序）
            'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
            'Accept': 'application/json, text/plain, */*',
            'Accept-Language': 'zh-CN,zh;q=0.9,en;q=0.8',
            'Accept-Encoding': 'gzip, deflate, br',

            # Chrome特有的Sec-Ch-Ua头（客户端提示）
            'Sec-Ch-Ua': '"Not_A Brand";v="8", "Chromium";v="120", "Google Chrome";v="120"',
            'Sec-Ch-Ua-Mobile': '?0',
            'Sec-Ch-Ua-Platform': '"Windows"',

            # 安全相关头
            'Sec-Fetch-Site': 'same-origin',
            'Sec-Fetch-Mode': 'cors',
            'Sec-Fetch-Dest': 'empty',

            # 连接控制
            'Connection': 'keep-alive',

            # 缓存控制
            'Cache-Control': 'no-cache',
            'Pragma': 'no-cache',
        }
